from __future__ import annotations

"""Compile evidence-backed user-visible requirements into the planning-state SSOT.

This stage never turns an unresolved state into a crash just because information is still
missing. Only unknowns whose host-owned ``blocks`` set names requirement selection may
stop this stage. Once prompt/reference semantics are resolved, the bounded model selects
testable requirements; implementation unknowns are generated by the host afterwards.
"""

from collections.abc import Mapping, Sequence
from copy import deepcopy
from typing import Any

from .minecraft_template_catalog import (
    CUSTOM_CAPABILITY_SENTINEL,
    capability_catalog_for_model,
    semantic_capability_choices,
)
from .planner_operation import planner_operation
from .planning_state_contract import ROUTE_SOURCES, validate_planning_state

_REQUIREMENT_TOOL = "submit_researched_requirements"
_SEMANTIC_CAPABILITY_CHOICES = semantic_capability_choices()
_SEMANTIC_CAPABILITY_CHOICE_SET = frozenset(_SEMANTIC_CAPABILITY_CHOICES)
_REQUIREMENT_PARAMETERS: dict[str, Any] = {
    "type": "object",
    "properties": {
        "requirements": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "statement": {"type": "string"},
                    "semantic_capability": {
                        "type": "string",
                        "enum": list(_SEMANTIC_CAPABILITY_CHOICES),
                    },
                    "prompt_refs": {"type": "array", "items": {"type": "string"}},
                    "evidence_refs": {"type": "array", "items": {"type": "string"}},
                    "acceptance": {"type": "array", "items": {"type": "string"}},
                },
                "required": [
                    "statement",
                    "semantic_capability",
                    "prompt_refs",
                    "evidence_refs",
                    "acceptance",
                ],
                "additionalProperties": False,
            },
        }
    },
    "required": ["requirements"],
    "additionalProperties": False,
}


def _text(value: Any) -> str:
    return " ".join(str(value or "").split()).strip()


def _strings(value: Any) -> list[str]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes, bytearray)):
        return []
    return list(dict.fromkeys(text for item in value if (text := _text(item))))


def _known_evidence_refs(state: Mapping[str, Any]) -> set[str]:
    refs: set[str] = set()
    rows = state.get("evidence", [])
    if not isinstance(rows, list):
        return refs
    for evidence in rows:
        if not isinstance(evidence, Mapping) or evidence.get("sufficient") is not True:
            continue
        refs.update(_strings(evidence.get("evidence_refs")))
    return refs


def _known_prompt_refs(state: Mapping[str, Any]) -> set[str]:
    refs = {"goal"}
    rows = state.get("known", [])
    if isinstance(rows, list):
        refs.update(
            str(item.get("known_id") or "")
            for item in rows
            if isinstance(item, Mapping) and str(item.get("known_id") or "")
        )
    return refs


def _prompt_ref_aliases(state: Mapping[str, Any]) -> dict[str, str]:
    """Map host-owned prompt receipts back to the canonical prompt-ref namespace.

    Small models sometimes copy provenance metadata such as ``prompt_sha256`` or a
    receipt ``text_sha256`` instead of the requested ``goal``/``known_*`` ID. Those
    values already prove authored-prompt provenance, so normalize only aliases that the
    host can derive from this exact state. Arbitrary model-authored IDs remain invalid.
    """

    aliases: dict[str, str] = {
        "goal": "goal",
        "prompt_sha256": "goal",
        "requested_prompt": "goal",
    }
    prompt_hash = _text(state.get("prompt_sha256"))
    if prompt_hash:
        aliases[prompt_hash] = "goal"

    goal = state.get("goal")
    if isinstance(goal, Mapping):
        source = goal.get("source")
        if isinstance(source, Mapping):
            receipt_hash = _text(source.get("text_sha256"))
            if receipt_hash:
                aliases[receipt_hash] = "goal"

    rows = state.get("known", [])
    if isinstance(rows, list):
        for item in rows:
            if not isinstance(item, Mapping):
                continue
            known_id = _text(item.get("known_id"))
            if not known_id:
                continue
            aliases[known_id] = known_id
            source = item.get("source")
            if not isinstance(source, Mapping):
                continue
            receipt_hash = _text(source.get("text_sha256"))
            if receipt_hash and receipt_hash != prompt_hash:
                aliases.setdefault(receipt_hash, known_id)
    return aliases


def _normalize_prompt_refs(state: Mapping[str, Any], value: Any) -> list[str]:
    aliases = _prompt_ref_aliases(state)
    return list(dict.fromkeys(aliases.get(ref, ref) for ref in _strings(value)))


def _resolved_context(state: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "goal": deepcopy(state.get("goal")),
        "known": deepcopy(state.get("known", [])),
        "references": deepcopy(state.get("references", [])),
        "scope_status": state.get("scope_status"),
        "resolved": deepcopy(state.get("resolved", [])),
        "evidence": [
            deepcopy(item)
            for item in state.get("evidence", [])
            if isinstance(item, Mapping) and item.get("sufficient") is True
        ],
    }


def _next_id(items: Sequence[Mapping[str, Any]], key: str, prefix: str) -> str:
    maximum = 0
    for item in items:
        raw = str(item.get(key) or "")
        if not raw.startswith(prefix):
            continue
        try:
            maximum = max(maximum, int(raw.removeprefix(prefix)))
        except ValueError:
            continue
    return f"{prefix}{maximum + 1:03d}"


def _rehash(state: dict[str, Any]) -> dict[str, Any]:
    from .planning_state_contract import _hash_without

    state["state_sha256"] = ""
    state["state_sha256"] = _hash_without(state, "state_sha256")
    return state


def _blocking_unknowns(
    state: Mapping[str, Any],
    *,
    stage: str = "requirement_selection",
) -> list[Mapping[str, Any]]:
    """Return only unresolved rows that explicitly block the requested host stage."""
    rows = state.get("unresolved", [])
    if not isinstance(rows, list):
        return []
    return [
        item
        for item in rows
        if isinstance(item, Mapping)
        and item.get("status") != "resolved"
        and stage in _strings(item.get("blocks"))
    ]


def _preserve_blocked_state(state: Mapping[str, Any]) -> dict[str, Any]:
    """Represent incomplete requirement knowledge in state instead of throwing it away."""
    value = deepcopy(dict(state))
    blocking = _blocking_unknowns(value, stage="requirement_selection")
    existing = [
        item
        for item in value.get("blockers", [])
        if isinstance(item, Mapping) and item.get("stage") != "requirement_selection"
    ]
    if blocking:
        existing.append(
            {
                "blocker_id": "blocker_requirement_selection",
                "stage": "requirement_selection",
                "statement": "Requirement selection is waiting for unresolved task-state knowledge.",
                "caused_by": [str(item.get("unresolved_id") or "") for item in blocking],
            }
        )
    value["blockers"] = existing
    value["plan_ready"] = False
    return _rehash(value)


def compile_researched_requirements(
    router: Any,
    prompt: str,
    state: Mapping[str, Any],
) -> dict[str, Any]:
    """Add requirement decisions and host-owned implementation research to the SSOT."""
    validate_planning_state(state, prompt=prompt)
    if _blocking_unknowns(state, stage="requirement_selection"):
        return _preserve_blocked_state(state)

    messages = [
        {
            "role": "system",
            "content": (
                "Compile independently testable, player-visible requirements from only the "
                "supplied canonical task state. Do not reinterpret the raw request and do not "
                "invent Minecraft APIs, files, classes, registrations, or implementation "
                "architecture. For each requirement select exactly one semantic_capability from "
                "the supplied host capability catalog; never invent or paraphrase capability IDs, "
                f"and use '{CUSTOM_CAPABILITY_SENTINEL}' only when no listed capability accurately "
                "describes the behavior. Cite prompt provenance structurally with prompt_refs: use "
                "only 'goal' or known_id values present in the supplied state; never copy source_id, "
                "text_sha256, prompt_sha256, or other receipt metadata into prompt_refs. Cite "
                "grounded external facts with evidence_refs. Every requirement needs at least one "
                "prompt_ref or evidence_ref. For reference-driven requirements, use only grounded "
                "reference evidence inside the resolved scope. Missing balance values or detailed "
                "mechanics are later design work, not a reason to omit an authored behavior "
                "requirement. Return behavior requirements and acceptance observations only."
            ),
        },
        {
            "role": "user",
            "content": str(
                {
                    "task_state": _resolved_context(state),
                    "semantic_capability_catalog": capability_catalog_for_model(),
                    "custom_capability": CUSTOM_CAPABILITY_SENTINEL,
                }
            ),
        },
    ]
    with planner_operation("researched_requirement_compile", output_tokens=2048):
        raw = router.generate_tool_decision(
            "planner",
            messages,
            tool_name=_REQUIREMENT_TOOL,
            parameters=_REQUIREMENT_PARAMETERS,
            description=(
                "Submit evidence-backed player-visible requirements for the resolved task state."
            ),
        )

    raw_requirements = raw.get("requirements") if isinstance(raw, Mapping) else None
    if not isinstance(raw_requirements, list) or not raw_requirements:
        raise ValueError(
            "PLANNING_REQUIREMENTS_EMPTY: planner returned no researched requirements"
        )

    allowed_evidence = _known_evidence_refs(state)
    allowed_prompt = _known_prompt_refs(state)
    requirement_decisions: list[dict[str, Any]] = []
    for index, item in enumerate(raw_requirements, start=1):
        if not isinstance(item, Mapping):
            raise ValueError("PLANNING_REQUIREMENT_SHAPE: requirement must be an object")
        statement = _text(item.get("statement"))
        semantic_capability = _text(item.get("semantic_capability")).casefold()
        prompt_refs = _normalize_prompt_refs(state, item.get("prompt_refs"))
        evidence_refs = _strings(item.get("evidence_refs"))
        acceptance = _strings(item.get("acceptance"))
        if not statement or not acceptance:
            raise ValueError(
                "PLANNING_REQUIREMENT_CONTENT: statement and acceptance are required"
            )
        if semantic_capability not in _SEMANTIC_CAPABILITY_CHOICE_SET:
            raise ValueError(
                "PLANNING_REQUIREMENT_CAPABILITY: unknown semantic capability: "
                + (semantic_capability or "<empty>")
            )
        invalid_prompt = [ref for ref in prompt_refs if ref not in allowed_prompt]
        if invalid_prompt:
            raise ValueError(
                "PLANNING_REQUIREMENT_PROMPT_REFS: unknown prompt refs: "
                + ", ".join(invalid_prompt)
            )
        invalid_evidence = [ref for ref in evidence_refs if ref not in allowed_evidence]
        if invalid_evidence:
            raise ValueError(
                "PLANNING_REQUIREMENT_EVIDENCE: unknown evidence refs: "
                + ", ".join(invalid_evidence)
            )
        if not prompt_refs and not evidence_refs:
            raise ValueError(
                "PLANNING_REQUIREMENT_PROVENANCE: requirement needs prompt or evidence basis"
            )
        requirement_decisions.append(
            {
                "requirement_id": f"req_{index:03d}",
                "statement": statement,
                "semantic_capability": semantic_capability,
                "prompt_refs": prompt_refs,
                "evidence_refs": evidence_refs,
                "acceptance": acceptance,
                "status": "implementation_research_pending",
            }
        )

    value = deepcopy(dict(state))
    value["blockers"] = [
        item
        for item in value.get("blockers", [])
        if not (isinstance(item, Mapping) and item.get("stage") == "requirement_selection")
    ]
    value["decisions"] = [
        item
        for item in value.get("decisions", [])
        if not (isinstance(item, Mapping) and item.get("decision_type") == "requirement")
    ]

    implementation_sources = list(ROUTE_SOURCES["implementation_research"])
    for requirement in requirement_decisions:
        value["decisions"].append(
            {
                "decision_id": f"d_{len(value['decisions']) + 1:03d}",
                "decision_type": "requirement",
                **deepcopy(requirement),
            }
        )
        unresolved_id = _next_id(value.get("unresolved", []), "unresolved_id", "u_")
        research_id = _next_id(value.get("research_queue", []), "research_id", "r_")
        value["unresolved"].append(
            {
                "unresolved_id": unresolved_id,
                "question": (
                    "How can this requirement be implemented correctly for the resolved "
                    f"Minecraft target: {requirement['statement']}"
                ),
                "reason": "implementation_method",
                "blocks": [requirement["requirement_id"], "implementation_plan"],
                "information_needed": (
                    "Verified reusable mod/code patterns, Minecraft API/source behavior, "
                    "required artifacts, dependencies, and verification obligations for: "
                    + requirement["statement"]
                ),
                "resolution_route": "implementation_research",
                "source_kinds": implementation_sources,
                "status": "open",
                "research_ref": research_id,
                "requirement_ref": requirement["requirement_id"],
            }
        )
        value["research_queue"].append(
            {
                "research_id": research_id,
                "resolves": [unresolved_id],
                "requirement_ref": requirement["requirement_id"],
                "objective": (
                    "Find evidence-backed implementation/reuse options for "
                    + requirement["statement"]
                ),
                "information_needed": (
                    "Concrete implementation patterns and all required support artifacts and "
                    "dependencies, without inventing APIs or assuming prompt vocabulary matches code."
                ),
                "source_kinds": implementation_sources,
                "queries": [],
                "status": "pending",
            }
        )

    value["plan_ready"] = False
    return _rehash(value)


__all__ = ["compile_researched_requirements"]
